#include <stdio.h>
#include <string.h>

#define MAXSIZE 9100
#define MAXNAMES 82

int txdhashes[MAXSIZE];
int num_txdhashes;
char names[MAXSIZE][MAXNAMES][50];
int num_names[MAXSIZE];
char txd_names[MAXSIZE][50];

static
int nfsu2_cshash(char *input)
{
	unsigned int result;
	int j;

	result = -1;
	j = 0;
	while (input[j]) {
		result *= 33;
		result += input[j];
		j++;
	}
	return result;
}

static
int idxfortxd(char *txd)
{
	int i;
	int hash;

	hash = nfsu2_cshash(txd);
	for (i = 0; i < num_txdhashes; i++) {
		if (txdhashes[i] == hash) {
			if (strcmp(txd, txd_names[i])) {
				printf("hash collision for %s and %s\n", txd, txd_names[i]);
			}
			return i;
		}
	}
	txdhashes[num_txdhashes] = hash;
	strcpy(txd_names[num_txdhashes], txd);
	num_txdhashes++;
	return num_txdhashes - 1;
}

int main()
{
	FILE *in, *out;
	char line[300];
	char *txd, *name;
	int idx;
	int i, j, k, offset;

	in = fopen("texturelist-extracted-from-fusez-mapeditor-thx.txt", "r");
	if (!in) {
		puts("can't open inputfile");
		return 1;
	}
	while (fgets(line, sizeof(line), in) && line[0]) {
		name = strstr(line, ",");
		if (name) {
			txd = line;
			*name = 0;
			name++;
			name[strlen(name) - 1] = 0; /*remove ending \n*/
			idx = idxfortxd(txd);
			if (num_names[idx] == MAXNAMES) {
				printf("need more MAXNAMES for %s\n", txd);
			} else {
				strcpy(names[idx][num_names[idx]], name);
				num_names[idx]++;
			}
		} else {
			printf("wrong input line: %s", line);
		}

	}
	fclose(in);

	out = fopen("../client/game_texturelist.c", "wb");
	if (!out) {
		puts("can't open outputfile");
		return 1;
	}
	fputs("/*autogenerated file*/\n", out);
	fputs("/*extracted from fusez map editor thx*/\n", out);
	fputs("int txd_hashes[] = {\n", out);
	for (i = 0; i < num_txdhashes; i++) {
		sprintf(line, "/*%d,%s*/0x%x,\n", i, txd_names[i], txdhashes[i]);
		fputs(line, out);
	}
	fputs("};\n", out);
	fputs("char *txd_names[] = {\n", out);
	for (i = 0; i < num_txdhashes; i++) {
		sprintf(line, "/*%d*/\"%s\",\n", i, txd_names[i]);
		fputs(line, out);
	}
	fputs("};\n", out);
	fputs("char *txd_textures[] = {\n", out);
	for (i = 0, k = 0; i < num_txdhashes; i++) {
		for (j = 0; j < num_names[i]; j++) {
			sprintf(line, "/*%d,%d,%d*/\"%s\",\n", k, i, j, names[i][j]);
			fputs(line, out);
			k++;
		}
	}
	fputs("};", out);
	offset = 0;
	fputs("int txd_textures_offset[] = {\n", out);
	for (i = 0; i < num_txdhashes; i++) {
		sprintf(line, "%d,\n", offset);
		fputs(line, out);
		offset += num_names[i];
	}
	fputs("};\n", out);
	fputs("char txd_numtextures[] = {", out);
	for (i = 0; i < num_txdhashes; i++) {
		sprintf(line, "%d,\n", num_names[i]);
		fputs(line, out);
	}
	fputs("};\n", out);

	fclose(out);
	return 0;
}
